name: 'Meri Awaaz: Connecting Citizens with Governments and Elected Officials'
markdown: redcarpet
highlighter: pygments
#url: http://staging.meriawaazapp.com
#url: http://localhost:4000
url: http://meriawaazapp.com
